/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Vercel from './../public/next.svg'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Fernando Besa Portfolio | Frontend Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-white flex flex-col justify-center p-32">
            <section className="grid grid-cols-2 gap-x-12">
              <div>
                <h1 className="text-black text-3xl inter">Frontend Web Developer | Fernando</h1>
                <p className="font-sm text-gray-500 text-sm max-w-prose mt-2 inter">I'm an aspiring frontend web developer with a passion for creating visually appealing and user-friendly websites. Proficient in HTML, CSS, JavaScript, and CSS frameworks such as Bootstrap and Foundation. Completed projects in a team setting using agile methodologies and following accessibility and responsive design best practices. Always seeking new challenges to improve my skills and eager to contribute to a company's success.</p>
              </div>
              <div className="text-black flex flex-col content-center items-center">
                <Image src={Vercel} height="500" width="500" alt="Hero Image" />
              </div>
            </section>
      </main>
    </>
  )
}
